# Copyright 2019-2022 VMware, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# you may obtain a copy of the License at
# http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
version: "3.7"

networks:
  fate-network:
    ipam:
      config:
        - subnet: 192.167.0.0/16

volumes:
  fate_flow_logs:
  download_dir:
  shared_dir_examples:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: <path-to-host-dir>/examples
  shared_dir_fate:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: <path-to-host-dir>/fate
  shared_dir_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: <path-to-host-dir>/data

services:
  fateboard:
    image: "${FATEBoard_IMAGE}:${FATEBoard_IMAGE_TAG}"
    ports:
      - "8080:8080"
    volumes:
      - ./confs/fateboard/conf:/data/projects/fate/fateboard/conf
      - fate_flow_logs:/data/projects/fate/fate_flow/logs
      - /etc/localtime:/etc/localtime:ro
    restart: always
    networks:
      - fate-network
    depends_on:
      - fateflow

  fateflow:
    image: "${FATEFlow_IMAGE}:${FATEFlow_IMAGE_TAG}"
    restart: always
    ports:
      - 9380:9380
      - 9360:9360
    volumes:
      - ./confs/spark/spark-defaults.conf:/data/projects/spark-3.1.3-bin-hadoop3.2/conf/spark-defaults.conf
      - shared_dir_fate:/data/projects/fate/fate
      - shared_dir_examples:/data/projects/fate/examples
      - download_dir:/data/projects/fate/fate/python/download_dir
      - fate_flow_logs:/data/projects/fate/fate_flow/logs
      - ./confs/fate_flow/conf/service_conf.yaml:/data/projects/fate/fate_flow/conf/service_conf.yaml
      - ./confs/fate_flow/conf/pulsar_route_table.yaml:/data/projects/fate/fate_flow/conf/pulsar_route_table.yaml
      - ./confs/fate_flow/conf/rabbitmq_route_table.yaml:/data/projects/fate/fate_flow/conf/rabbitmq_route_table.yaml
      - ./confs/eggroll/conf:/data/projects/fate/eggroll/conf
      - ./shared_dir/data/model_local_cache:/data/projects/fate/fate_flow/model_local_cache
      - /etc/localtime:/etc/localtime:ro
    networks:
      fate-network:
        ipv4_address: 192.167.0.100
    healthcheck:
      test: ["CMD", "curl", "-f", "-X GET", "http://192.167.0.100:9380/v2/server/fateflow"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    command:
    - "/bin/bash"
    - "-c"
    - |
        set -x
        sed -i "s/int(party.party_id)/str(party.party_id)/g" /data/projects/fate/fate/python/fate/arch/federation/backends/pulsar/_federation.py
        cp /data/projects/fate/fate_flow/conf/pulsar_route_table.yaml /data/projects/fate/fate_flow/pulsar_route_table.yaml
        cp /data/projects/fate/fate_flow/conf/rabbitmq_route_table.yaml /data/projects/fate/fate_flow/rabbitmq_route_table.yaml
        sleep 5 && python fate_flow/python/fate_flow/fate_flow_server.py
    environment:
      FATE_PROJECT_BASE: "/data/projects/fate"
      FATE_FLOW_UPLOAD_MAX_NUM: "1000000"
      FATE_FLOW_UPLOAD_MAX_BYTES: "104868093952"
      FATE_LOG_LEVEL: "INFO"

  mysql:
    image: "${MySQL_IMAGE}:${MySQL_IMAGE_TAG}"
    expose:
      - 3306
    volumes:
      - ./confs/mysql/init:/docker-entrypoint-initdb.d/
      - ./shared_dir/data/mysql:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    networks:
      - fate-network
    cap_add:
      - SYS_NICE

  osx:
    image: "${RegistryURI}${OSX_IMAGE}:${OSX_IMAGE_TAG}"
    restart: always
    ports:
      - "9370:9370"
    environment:
      PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION: python
    volumes:
      - ./confs/osx/conf/:/data/projects/fate/osx/conf/broker/
      - /etc/localtime:/etc/localtime:ro
    networks:
      - fate-network
    command: ["sh", "-c", "java  -XX:+UseG1GC -XX:G1HeapRegionSize=16m -XX:G1ReservePercent=25 -XX:InitiatingHeapOccupancyPercent=30 -XX:SoftRefLRUPolicyMSPerMB=0 -verbose:gc -Xloggc:/dev/shm/rmq_srv_gc_%p_%t.log -XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:+PrintGCApplicationStoppedTime -XX:+PrintAdaptiveSizePolicy -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=5 -XX:GCLogFileSize=30m -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/oom/heapdump.hprof  -server -Xms4g -Xmx4g -XX:-OmitStackTraceInFastThrow -XX:+AlwaysPreTouch -XX:MaxDirectMemorySize=15g -XX:-UseLargePages -XX:-UseBiasedLocking  -cp conf/broker/:lib/*:extension/*:/data/projects/fate/osx/lib/osx-broker-1.0.0.jar org.fedai.osx.broker.Bootstrap -c /data/projects/fate/osx/conf"]

  # rabbitmq:
  #   image: "${RabbitMQ_IMAGE}:${RabbitMQ_IMAGE_TAG}"
  #   ports:
  #     - "5672:5672"
  #     - "15672:15672"
  #   environment:
  #     RABBITMQ_DEFAULT_USER: fate
  #     RABBITMQ_DEFAULT_PASS: fate
  #     RABBITMQ_USER: fate
  #     RABBITMQ_PASSWORD: fate
  #     RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: "-rabbit max_message_size 536870912"
  #   volumes:
  #     - ./confs/rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins
  #     - ./shared_dir/data/rabbitmq:/var/lib/rabbitmq
  #   restart: always
  #   networks:
  #     - fate-network

  # pulsar:
  #   image: "${Pulsar_IMAGE}:${Pulsar_IMAGE_TAG}"
  #   ports:
  #     - "6650:6650"
  #     - "6651:6651"
  #     - "8001:8080"
  #   volumes:
  #     - ./confs/pulsar/standalone.conf:/pulsar/conf/standalone.conf
  #     # - ./shared_dir/data/pulsar:/pulsar/data
  #     - /etc/localtime:/etc/localtime:ro
  #   command:
  #     ["/bin/bash", "-c", "bin/pulsar standalone -nss"]
  #   restart: always
  #   networks:
  #     - fate-network
      
  client:
    image: "${Client_IMAGE}:${Client_IMAGE_TAG}"
    ports:
      - "20000:20000"
    restart: always
    environment:
      FATE_FLOW_IP: "fateflow"
      FATE_FLOW_PORT: "9380"
      FATE_SERVING_HOST: "fate-serving:8059"
      NOTEBOOK_HASHED_PASSWORD: "${NOTEBOOK_HASHED_PASSWORD}"
    volumes:
      - download_dir:/data/projects/fate/download_dir
      - shared_dir_examples:/data/projects/fate/examples
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - fateflow
    networks:
      - fate-network
    command: ["bash", "-c", "pipeline init --ip $${FATE_FLOW_IP} --port $${FATE_FLOW_PORT} && flow init --ip $${FATE_FLOW_IP} --port $${FATE_FLOW_PORT} && jupyter notebook --ip=0.0.0.0 --port=20000 --allow-root --debug --NotebookApp.notebook_dir='/data/projects/fate/' --no-browser --NotebookApp.token='' --NotebookApp.password=$${NOTEBOOK_HASHED_PASSWORD} "]
